version: '3.4'

services:
  locationdb:
    image: postgres
  
  assetdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pgadmin:
    image: dpage/pgadmin4

  location.api:
    image: ${DOCKER_REGISTRY-}locationapi
    build:
      context: .
      dockerfile: Services/Location/Location.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data: